### ISSUE TITLE
ZZLL missing alg

### ISSUE THREAD

**Issue by RGBtryhard** [tao-yu/Alg-Trainer#12]
The T6 set of ZZLL has a missing alg it is the [ R U R U' R2 U' D R' U2 R U2 D' R ] (OxO) alg
If you set them to go in order it does T6 0/0 twice and skips that one, if its random you will never get that alg.

**Comment by tao-yu** [comment]
Hello there,

While verifying this issue I noticed that the ZZLL algs on the trainer are from an older ZBLL sheet, with some algs having much better alternatives, so I decided to replace the algs entirely instead of merely fixing this one problem.

The new ZZLL set was created by removing all non-ZZLL algs from the Jabari-Justin-Tao ZBLL set. This time I automated the process using a script (I believe it was done manually last time) so there should not be any issues with missing algs. 

There is a chance that the order may now be different to what it was before, but now it should match the order of the Jabari-Justin-Tao set, which is what I think it should have followed in the first place. 

Thank you for bringing this issue to my attention, especially as such issues things can be hard to find by chance.

**Comment by RGBtryhard** [comment]
Wow that was quick, thanks you are a legend.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
