### ISSUE TITLE
Incorrect algorithm

### ISSUE THREAD

**Issue by L1meDaBestest** [tao-yu/Alg-Trainer#14]
In the first ZBLL tab in U6, the fifth case (when going in order) starts with a U2 AUF instead of U. Also the main body of the algorithm is wrong. It should look something like this U2 R U R2 D' R U' R' D R2 U' R' U R U' R'

**Comment by tao-yu** [comment]
Hi, sorry for the late response, but I do not see a discrepancy here. The fifth alg in U6 is [U R U R2 D' R U R' D R2 U2 R'](https://github.com/tao-yu/Alg-Trainer/blob/d71be61a7020b6171236ff2b33776cc913a98578/js/alg_list.js#L94), which [solves](https://alg.cubing.net/?alg=R_U_R-_U-_R_U_R2-_D-_R_U_R-_D_R2-_U-_R-_U2-_%2F%2F_inverse_of_your_alg%0AU_R_U_R2_D-_R_U_R-_D_R2_U2_R-_%2F%2F_alg_that_is_currently_in_trainer%0A%2F%2Fcube_ends_up_solved) the same case as U2 R U R2 D' R U' R' D R2 U' R' U R U' R' from the same angle (while being a faster alg). 

I do not remember if this has always been the case or if I fixed it and simply forgot to close this issue. In any case, I am closing this issue now because I believe it has been resolved.
