### ISSUE TITLE
Scramble doesn't show preorientation

### ISSUE THREAD

**Issue by tussosedan** [tao-yu/Alg-Trainer#6]
This is causing a discrepancy between scrambling on a real cube vs what is shown on the screen.

**Comment by tussosedan** [comment]
Additional related issue is that viewing previous scrambles shows the virtual and visual cubes without preorientation, which means that you see differently oriented cases than what you really did.

**Comment by povlhp** [comment]
Same issue here, even if I change colors to yellow on top (matches all my cheat sheets / drawings elsewhere), then I get white stickers on top - including corners, which should not be moved up from bottom layer.

**Comment by tao-yu** [comment]
Hi thanks for bringing this issue to my attention again. This wasn't a difficult issue to change, however, I had long considered this not to be a necessary feature since people who want to have yellow on top can simply hold their cube with yellow on top while scrambling, and enter z2 into the first preorientation setting box. 

However, after giving the issue more thought I realize there might indeed be some situations where showing preorientation could be useful, so I decided to implement the feature after all. I have also added some notes on how to achieve the correct orientation while scrambling underneath the orientation settings.
